@URL_DEV= http://127.0.0.1:8080/api/v1

POST {{URL_DEV}}/user/signup
Content-Type: application/json

{
    "username": "quanghai",
    "email": "quanghai@gmail.com",
    "password": "123abc",
    "mobile": "0862515616"
}

###
POST {{URL_DEV}}/user/signin
Content-Type: application/json

{
    "email": "quanghai@gmail.com",
    "password": "123abc"
}
