@URL_DEV= http://localhost:8080/api/v1

POST {{URL_DEV}}/user/signup
Content-Type: application/json

{
    "username": "tuananh2",
    "email": "tuananh@gmail.com",
    "password": "123abc",
    "mobile": "0902235500"
}

###
POST http://localhost:8080/api/v2/user/signin
